[phases.setup]
aptPkgs = [
    "libglib2.0-0",
    "libglib2.0-dev", 
    "libsdl2-2.0-0",
    "libsdl2-mixer-2.0-0",
    "libsdl2-image-2.0-0",
    "libsdl2-ttf-2.0-0",
    "libxext6",
    "libxrender1",
    "libx11-6",
    "libsm6",
    "libasound2",
    "libpulse0"
]